//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Azure_0517.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Discount
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Discount()
        {
            this.ReservationBookeds = new HashSet<ReservationBooked>();
        }
    
        public int Dis_ID { get; set; }
        public string Dis_Title { get; set; }
        public int Dis_RestaurantID { get; set; }
        public string Dis_Content { get; set; }
        public System.DateTime Dis_Start { get; set; }
        public Nullable<System.DateTime> Dis_End { get; set; }
        public byte[] Dis_Picture { get; set; }
    
        public virtual Restaurant Restaurant { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReservationBooked> ReservationBookeds { get; set; }
    }
}
