//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Azure_0517.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gift_Detail
    {
        public int GiftDet_ID { get; set; }
        public int GiftDet_MemberID { get; set; }
        public int GiftDet_GiftID { get; set; }
        public Nullable<System.DateTime> GiftDet_GetDate { get; set; }
        public int GiftDet_GetQuantity { get; set; }
    
        public virtual Gift Gift { get; set; }
        public virtual Member Member { get; set; }
    }
}
