//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Azure_0517.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gift
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Gift()
        {
            this.Gift_Detail = new HashSet<Gift_Detail>();
        }
    
        public int Gift_ID { get; set; }
        public string Gift_Name { get; set; }
        public string Gift_Content { get; set; }
        public int Gift_Point { get; set; }
        public int Gift_CreatedAdmini { get; set; }
        public System.DateTime Gift_CreatedDate { get; set; }
        public Nullable<int> Gift_Quantity { get; set; }
        public byte[] Gift_Picture { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gift_Detail> Gift_Detail { get; set; }
        public virtual Member Member { get; set; }
    }
}
