//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Azure_0517.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Picture
    {
        public int Pic_ID { get; set; }
        public Nullable<int> Pic_NewsID { get; set; }
        public Nullable<int> Pic_Restaurant { get; set; }
        public byte[] Pic_Picture { get; set; }
        public string Pic_Content { get; set; }
        public string Pic_title { get; set; }
    
        public virtual News News { get; set; }
        public virtual Restaurant Restaurant { get; set; }
    }
}
