//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Azure_0517.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QA_system
    {
        public int QA_ID { get; set; }
        public Nullable<int> QA_MemberID { get; set; }
        public Nullable<int> QA_AdministratorID { get; set; }
        public Nullable<int> QA_RestaurantID { get; set; }
        public System.DateTime QA_CreateDate { get; set; }
        public Nullable<System.DateTime> QA_AnswerdDate { get; set; }
        public string QA_Content { get; set; }
        public string QA_Answer { get; set; }
        public Nullable<bool> QA_MemkTalk { get; set; }
        public Nullable<bool> QA_ResTalk { get; set; }
        public Nullable<bool> QA_AdmTalk { get; set; }
    
        public virtual Member Member { get; set; }
        public virtual Member Member1 { get; set; }
        public virtual Restaurant Restaurant { get; set; }
    }
}
