//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Azure_0517.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Restaurant
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Restaurant()
        {
            this.Comments = new HashSet<Comment>();
            this.Discounts = new HashSet<Discount>();
            this.News = new HashSet<News>();
            this.Pictures = new HashSet<Picture>();
            this.QA_system = new HashSet<QA_system>();
            this.Reports = new HashSet<Report>();
            this.ReservationOpeneds = new HashSet<ReservationOpened>();
            this.Type_Detail = new HashSet<Type_Detail>();
        }
    
        public int Res_ID { get; set; }
        public string Res_Name { get; set; }
        public string Res_Account { get; set; }
        public string Res_Password { get; set; }
        public string Res_Address { get; set; }
        public string Res_Email { get; set; }
        public Nullable<int> Res_City { get; set; }
        public string Res_Phone { get; set; }
        public Nullable<int> Res_MaxConsumption { get; set; }
        public Nullable<int> Res_MinConsumption { get; set; }
        public Nullable<decimal> Res_StarRate { get; set; }
        public string Res_IntroductionContext { get; set; }
        public string Res_WorkingDate { get; set; }
        public byte[] Res_PayBy { get; set; }
        public Nullable<int> Res_Seats { get; set; }
        public Nullable<int> Res_ParkingSeats { get; set; }
        public bool Res_TenPercentService { get; set; }
        public byte[] Res_HomePagePicture { get; set; }
        public int Res_RoleID { get; set; }
        public System.DateTime Res_CreateDate { get; set; }
        public bool Res_QAEnable { get; set; }
        public string Res_TaxID { get; set; }
    
        public virtual City City { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Discount> Discounts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<News> News { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Picture> Pictures { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QA_system> QA_system { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Report> Reports { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReservationOpened> ReservationOpeneds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Type_Detail> Type_Detail { get; set; }
    }
}
