//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Azure_0517.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Taste_ItEntities : DbContext
    {
        public Taste_ItEntities()
            : base("name=Taste_ItEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AccuseType> AccuseTypes { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<Comment> Comments { get; set; }
        public virtual DbSet<Discount> Discounts { get; set; }
        public virtual DbSet<Gift> Gifts { get; set; }
        public virtual DbSet<Gift_Detail> Gift_Detail { get; set; }
        public virtual DbSet<Member> Members { get; set; }
        public virtual DbSet<News> News { get; set; }
        public virtual DbSet<Picture> Pictures { get; set; }
        public virtual DbSet<QA_system> QA_system { get; set; }
        public virtual DbSet<Report> Reports { get; set; }
        public virtual DbSet<ReservationBooked> ReservationBookeds { get; set; }
        public virtual DbSet<ReservationOpened> ReservationOpeneds { get; set; }
        public virtual DbSet<Restaurant> Restaurants { get; set; }
        public virtual DbSet<Right> Rights { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<StatusType> StatusTypes { get; set; }
        public virtual DbSet<SubType> SubTypes { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TheType> TheTypes { get; set; }
        public virtual DbSet<Type_Detail> Type_Detail { get; set; }
    }
}
